// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5kKFd2Ttk9ihqoajwHC_pf2crM2qxyx8',
    appId: '1:687680344006:web:e061e0ee24e3fe7bc8ecc7',
    messagingSenderId: '687680344006',
    projectId: 'payplus-6jabarz',
    authDomain: 'payplus-6jabarz.firebaseapp.com',
    storageBucket: 'payplus-6jabarz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1kWA_4Vjjua78SbfSjr7Xuq1qaKoyM_8',
    appId: '1:687680344006:android:a06692fffb6c3a9fc8ecc7',
    messagingSenderId: '687680344006',
    projectId: 'payplus-6jabarz',
    storageBucket: 'payplus-6jabarz.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5kKFd2Ttk9ihqoajwHC_pf2crM2qxyx8',
    appId: '1:687680344006:web:617e3d7c360b4ab0c8ecc7',
    messagingSenderId: '687680344006',
    projectId: 'payplus-6jabarz',
    authDomain: 'payplus-6jabarz.firebaseapp.com',
    storageBucket: 'payplus-6jabarz.firebasestorage.app',
  );
}
